POST http://localhost:3000/api/clients/applications
Content-Type: application/json

{
    "client_id": "fd83450d-df2f-4ecc-bd1d-8006f4cdf5e2",
    "products":[
        {
            "id": "0a454ce4-03b6-437d-b1f2-9c51ca4b5e1d",
            "count": 10

        },
          {
            "id": "378157e4-c826-4910-b581-8be144f1cafc",
            "count": 20
        }
    ]
}
